---
sudo: required
language: python
python: "3.6"

env:
    DOCKER_COMPOSE_VERSION: 1.19.0

services:
  - docker

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - ls
  - file docker-compose
  - sudo mv docker-compose /usr/local/bin/
  - ls -l /usr/local/bin


install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: tests
      env: TEST=passing_python
      script:
        - python passing_apps/flask/run_tests.py
    - env: TEST=base_python
      script:
        - python base_web_apps/flask/run_tests.py
    - env: TEST=base_java
      script:
        - ls -l /usr/local/bin 
        - cd base_web_apps/java && docker-compose pull
        - docker-compose build
        - docker-compose up -d
        - cd ../..
        - sleep 2
        - python base_web_apps/java/run_tests.py



